name: build_the_app

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Splunk app
        uses: VatsalJagani/splunk-app-action@v4
        with:
          app_dir: "package"
          is_app_inspect_check: false
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}