name: build_the_app

on:
    push:
      tags:
        - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Splunk app
        uses: VatsalJagani/splunk-app-action@v4
        with:
          app_dir: "package"
          is_app_inspect_check: false
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            files: App-Build-*